In [1]:
import numpy as np

In [2]:
print (np.__version__)  #打印numpy的版本

1.16.2


In [3]:
np.show_config()   #numpy的配置说明

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'F:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'F:/Anaconda\\Library\\include']
blas_opt_in

In [4]:
O = np.zeros(10)
print( O ) #创建一个长度为10的空向量（零向量） 0默认为浮点数

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
O = np.zeros( (10,10))                   #一个数组的内存大小
print("%d bytes" %(O.size * O.itemsize)) #size表示数组的元素个数，itemsize表示元素的字节长度

800 bytes


In [6]:
np.info( np.add ) #numpy中add函数的说明文档

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
help( np.info )

Help on function info in module numpy:

info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000002AF33A1BE10>, toplevel='numpy')
    Get help information for a function, class, or module.
    
    Parameters
    ----------
    object : object or str, optional
        Input object or name to get information about. If `object` is a
        numpy object, its docstring is given. If it is a string, available
        modules are searched for matching objects.  If None, information
        about `info` itself is returned.
    maxwidth : int, optional
        Printing width.
    output : file like object, optional
        File like object that the output is written to, default is
        ``stdout``.  The object has to be opened in 'w' or 'a' mode.
    toplevel : str, optional
        Start search at this level.
    
    See Also
    --------
    source, lookfor
    
    Notes
    -----
    When used interactively with an object, ``np.info(obj)`` is equivalent
    to

In [8]:
#创建一个长度为10并且除了第五个值为1的空向量
X= np.zeros(10)
X[4] = 1
print( X )

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
#创建一个值域范围从10到49的向量
X = np.arange( 10,50 )
print( X )

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#反转一个向量(第一个元素变为最后一个)
X = np.arrange( 10 )
X = X[::-1]
print( X )

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
#反转一个向量(第一个元素变为最后一个)
X = np.arange( 10 )
X = X[::-1]
print( X )

[9 8 7 6 5 4 3 2 1 0]


In [12]:
#创建一个 3x3 并且值从0到8的矩阵
X = np.arange( 9 ).reshape( 3,3 )
print( X )

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#找到数组[1,2,0,0,4,0]中非0元素的位置索引
X = np.nonzero( [1,2,0,0,4,0] )
print( X )

(array([0, 1, 4], dtype=int64),)


In [14]:
X = np.zero( [1,2,0,0,4,0] )
print( X )

AttributeError: module 'numpy' has no attribute 'zero'

In [15]:
[1,2,0,0,4,0].itemsize()

AttributeError: 'list' object has no attribute 'itemsize'

In [16]:
#创建一个 3x3 的单位矩阵
X = np.eye(3)
print( X )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#创建一个 3x3x3的随机数组
X = np.random.random( (3,3,3) ) #3*3*3个0-1的浮点数
print( X )

[[[0.71779097 0.46578828 0.26481204]
  [0.96535221 0.93309443 0.69765717]
  [0.60173659 0.00796215 0.31236684]]

 [[0.19369857 0.17375654 0.65244505]
  [0.48483057 0.08341651 0.51602254]
  [0.76168599 0.22504122 0.98731343]]

 [[0.87930086 0.75165387 0.30543901]
  [0.18229334 0.75930621 0.98335457]
  [0.70289214 0.92045689 0.0818344 ]]]


In [18]:
#创建一个 10x10 的随机数组并找到它的最大值和最小值
X = np.random.random( (10,10) )
max,min = X.max(),X.min()
print( max,min )

0.9811139383965852 0.004681663276870696


In [19]:
# 创建一个长度为30的随机向量并找到它的平均值
X = np.random.random(30)
avg = X.mean()
print( avg )

0.5451840021085338


In [20]:
#创建一个二维数组，其中边界值为1，其余值为0 
X = np.ones( (5,10) )
X[1:-1,1:-1] = 0
print( X )

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
#用0填充数组的边界
X = np.ones( (5,5) )
X = np.pad( Z , pad_width=1 , mode='consistant' , constant_values=0 )

NameError: name 'Z' is not defined

In [22]:
#用0填充数组的边界
X = np.ones( (5,5) )
X = np.pad( X , pad_width=1 , mode='consistant' , constant_values=0 )

KeyError: 'consistant'

In [23]:
#用0填充数组的边界
X = np.ones( (5,5) )
X = np.pad( X , pad_width=1 , mode='constant' , constant_values=0 )

In [24]:
print( X )

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [25]:
# 以下表达式运行的结果分别是什么
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)   #浮点数的误差

nan
False
False
nan
False


In [26]:
#创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
X = np.diag( np.arange(1,5),k=-1 ) #第二个参数用来调整偏离对角线的距离
print( X )

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
#创建一个8x8 的矩阵，并且设置成棋盘样式
X = np.zeros( (8,8),dtype = int )
X[1::2,::2] = 1
X[::2,1::2] = 1
print( X )

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#一个 (6,7,8) 形状的数组，求其第100个元素的在数组中的索引(x,y,z)
print( np.unravel_index(100,(6,7,8)) )

(1, 5, 4)


In [29]:
print( np.unravel_index(10,(6,7,8)) )

(0, 1, 2)
