In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series( [4, 7, -5, 3] )
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series( [4, 7, -5, 3], index=['d', 'b', 'a', 'c'] )
obj2  #自定义索引

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
#通过索引选取一个或者一组值
obj2['a']

-5

In [9]:
obj2['d'] = 6
obj2['c','a','d']

KeyError: ('c', 'a', 'd')

In [10]:
obj2['d'] = 6
obj2[ ['c','a','d'] ]

c    3
a   -5
d    6
dtype: int64

In [11]:
#根据布尔型数组进行过滤
obj2[ obj2>0 ]

d    6
b    7
c    3
dtype: int64

In [12]:
#标量乘法
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
#数学函数
np.exp(obj2)

NameError: name 'np' is not defined

In [14]:
import numpy as np

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
#Series类似于字典，可以用在许多原本需要字典参数的函数中
'b' in obj2

True

In [17]:
0.006738 in obj2

False

In [18]:
np.log(obj2)

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


d    1.791759
b    1.945910
a         NaN
c    1.098612
dtype: float64

In [19]:
obj2 = pd.Series( [4, 7, -5, 3], index=['d', 'b', 'a', 'c'] )

In [20]:
4 in obj2

False

In [21]:
'b' in obj2

True

In [22]:
#通过字典来创建Series
sdata = { 'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah': 5000 }

In [23]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
#传入排好序的字典的键改变顺序，找不到值得结果为NaN，'Utah'不在states中，被除去
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series (sdata, index = states )
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
#isnull notnull可以检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
#根据运算的索引标签自动对齐数据  类似数据库的join
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3+obj4 #Utah NaN

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
#Series对象本身及其索引都有一个name属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
#索引可以通过赋值的方式修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [33]:
#DataFrame   表格型数据结构  既有行索引也有列索引
#建立DataFrame 直接传入一个由等长列表或Numpy数组组成的字典：
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2] }
frame = pd.DataFrame( data )

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
#对于特别大的DataFrame， head方法会选取前五行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
#如果指定了列序列，DataFrame的列会按照指定顺序进行排列
pd.DataFrame( data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
#如果传入的列在数据中找不到，就会产生缺失值
frame2 = pd.DataFrame( data, columns=['year', 'state', 'pop', 'debt'],
                             index = ['one', 'two', 'three', 'four', 'five'] )
frame2

ValueError: Shape of passed values is (6, 4), indices imply (5, 4)

In [38]:
#如果传入的列在数据中找不到，就会产生缺失值
frame2 = pd.DataFrame( data, columns=['year', 'state', 'pop', 'debt'],
                             index = ['one', 'two', 'three', 'four', 'five', 'six'] )
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [39]:
frame2.colunms

AttributeError: 'DataFrame' object has no attribute 'colunms'

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
#通过类似字典标记的方式，可以将DataFrame的列获取为一个Series
frame2[['state','pop']]

state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9
six    Nevada  3.2

In [42]:
frame['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [43]:
#获取行属性
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [44]:
#列可以通过赋值的方式赋上一个或者一组值
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [45]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val 
#将列表或数组赋给某个列时，其长度必须跟DataFrame的长度相匹配。如果赋值的是一个Series
#就会精确匹配DataFrame的索引，所有空位都将被填上缺失值
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [47]:
val = pd.Series([-1.2, -1.5, -1.7])
frame2['debt'] = val 
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [48]:
val = pd.Series([-1.2, -1.5, -1.7, 1.2, 1.3, 1.4])
frame2['debt'] = val 
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [49]:
#新建一个“是否为Ohio”的列,不能用frame2.eastern创建新的列
frame2['eastern'] = frame2.state =='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [50]:
#del方法删除列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
#嵌套字典传入DataFrame
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame( pop )
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [52]:
#对frame3进行转置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [53]:
#若指定索引，则按该索引排列
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [54]:
#设置index和columns的name属性
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [55]:
#跟Series一样，values属性会以二维ndarray的形式返回
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [56]:
#如果各列的数据类型不同，则dtype就会选用能兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [57]:
#索引对象
#构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [58]:
index[1:]

Index(['b', 'c'], dtype='object')

In [59]:
#Index对象是不可变的，不能对其进行修改
index[1] = 'd'

TypeError: Index does not support mutable operations

In [60]:
#不可变可以使Index对象在多个数据结构之间安全共享
labels = pd.Index( np.arange(3) )
labels

Int64Index([0, 1, 2], dtype='int64')

In [61]:
obj2 = pd.Series( [0.5, 1.5, 2.1], index = labels )
obj2

0    0.5
1    1.5
2    2.1
dtype: float64

In [62]:
obj2.index is labels

True

In [63]:
#Index的功能也类似一个固定大小的集合
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [64]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [65]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [66]:
#与python的集合不同，pandas的Index可以包含重复的标签
dup_labels = pd.Index( ['foo', 'foo', 'bar', 'bar'] )
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
#Index的方法
#append              连接另一个Index对象，产生一个新的Index
#difference         计算差集
#intersection       计算交集
#union              计算并集
#delete             删除索引i处的元素，并得到新的Index
#drop               删除传入的值，并得到新的Index
#insert             将元素插入到索引i处，并得到新的Index
#is_monotonic       当各元素均大于等于前一个元素时，返回True
#is_unique          当Index没有重复值时，返回True
#unique             计算Index中只有唯一值的数组（删除重复的）